version: '1'
services:
  atenciones-service:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "8081:8081"

    environment:
      SPRING.DATASOURCE.URL= "jdbc:oracle:thin:@e2zmyh5tedwodp39_tp?TNS_ADMIN=/app/Wallet"
      SPRING.DATASOURCE.USERNAME= "FS12026"
      SPRING.DATASOURCE.PASSWORD= "ClaseFullStack1-"
     
    restart: always